# Text Preprocessing

1. Read the _childrens_books.csv_ file into a Jupyter Notebook
2. Within the Description column:
* Make all the text lowercase
* Remove all \xa0 characters
* Remove all punctuation

In [43]:
import pandas as pd
import os
pd.set_option('display.max_colwidth', None)  # Display full text in DataFrame cells

In [44]:
data = pd.read_csv('childrens_books.csv')
data.head()

,Ranking,Title,Author,Year,Rating,Description
0,1,Where the Wild Things Are,Maurice Sendak,1963,4.25,"Where the Wild Things Are follows Max, a young boy who, after being sent to his room for misbehaving, imagines sailing to an island filled with wild creatures. As their king, Max tames the beasts and eventually returns home to find his supper waiting for him. This iconic book explores themes of imagination, adventure, and the complex emotions of childhood, all captured through Sendak's whimsical illustrations and story."
1,2,The Very Hungry Caterpillar,Eric Carle,1969,4.34,"The Very Hungry Caterpillar tells the story of a caterpillar who eats through a variety of foods before eventually becoming a butterfly. Eric Carle’s use of colorful collage illustrations and rhythmic text has made this book a beloved classic for young readers. The simple, engaging story introduces children to days of the week, counting, and the concept of metamorphosis. It’s a staple in early childhood education."
2,3,The Giving Tree,Shel Silverstein,1964,4.38,"The Giving Tree is a touching and bittersweet story about a tree that gives everything it has to a boy over the course of his life. As the boy grows up, he takes more from the tree, and the tree continues to give, even when it has little left. Silverstein’s minimalist text and illustrations convey deep themes of unconditional love, selflessness, and the passage of time. It has sparked much discussion about relationships and sacrifice."
3,4,Green Eggs and Ham,Dr. Seuss,1960,4.31,"In Green Eggs and Ham, Sam-I-Am tries to convince a reluctant character to try a dish of green eggs and ham, despite his resistance. Through repetition and rhyme, Dr. Seuss’s classic story about being open to new experiences encourages children to be adventurous and try things outside their comfort zone. The playful illustrations and humorous dialogue make it a fun and educational read for young readers."
4,5,Goodnight Moon,Margaret Wise Brown,1947,4.31,"Goodnight Moon is a gentle, rhythmic bedtime story where a little bunny says goodnight to everything in his room, from the moon to the ""quiet old lady whispering hush."" Its repetitive structure and comforting tone make it ideal for young children. The simple illustrations by Clement Hurd complement the soothing nature of the story, making it a beloved classic for sleep-time reading."

In [28]:
data.Description.iloc[0]

"Where the Wild Things Are\xa0follows Max, a young boy who, after being sent to his room for misbehaving, imagines sailing to an island filled with wild creatures. As their king, Max tames the beasts and eventually returns home to find his supper waiting for him. This iconic book explores themes of imagination, adventure, and the complex emotions of childhood, all captured through Sendak's whimsical illustrations and story."

In [ ]:
# funtion to clean the description column of the dataframe
def lower_replace_special_char(series):
    """
    This function takes a pandas Series as input and performs the following operations:
    1. Converts all text to lowercase.
    2. Replaces special characters with spaces.
    
    Parameters:
    series (pd.Series): The input pandas Series containing text data.
    
    Returns:
    pd.Series: A new pandas Series with cleaned text data.
    """
    # Convert to lowercase    
    output = series.str.lower()
    # Replace square brackets with empty string and remove special characters
    output = output.str.replace(r'\[.*?\]', '', regex=True)
    output = output.str.replace(r'[^\w\s]', '', regex=True)
    # Replace non-breaking spaces with regular spaces
    output = output.str.replace(r'\xa0', ' ', regex=True)
    return output

In [39]:
df = data.copy()

In [40]:
df['Description_clean'] = lower_replace_special_char(df.Description)

In [41]:
df.Description_clean.iloc[0]

'where the wild things are follows max a young boy who after being sent to his room for misbehaving imagines sailing to an island filled with wild creatures as their king max tames the beasts and eventually returns home to find his supper waiting for him this iconic book explores themes of imagination adventure and the complex emotions of childhood all captured through sendaks whimsical illustrations and story'

In [42]:
df.Description_clean.iloc[0]

'where the wild things are follows max a young boy who after being sent to his room for misbehaving imagines sailing to an island filled with wild creatures as their king max tames the beasts and eventually returns home to find his supper waiting for him this iconic book explores themes of imagination adventure and the complex emotions of childhood all captured through sendaks whimsical illustrations and story'

## 2. Text Preprocessing with spaCy

In addition to the lowercasing and special character removal from the previous assignment, within the cleaned Description column:
* Tokenize the text
* Lemmatize the text
* Remove stop words

In [50]:
import spacy
nlp = spacy.load("en_core_web_sm")

In [47]:
df.head(2)

,Ranking,Title,Author,Year,Rating,Description,Description_clean
0,1,Where the Wild Things Are,Maurice Sendak,1963,4.25,"Where the Wild Things Are follows Max, a young boy who, after being sent to his room for misbehaving, imagines sailing to an island filled with wild creatures. As their king, Max tames the beasts and eventually returns home to find his supper waiting for him. This iconic book explores themes of imagination, adventure, and the complex emotions of childhood, all captured through Sendak's whimsical illustrations and story.",where the wild things are follows max a young boy who after being sent to his room for misbehaving imagines sailing to an island filled with wild creatures as their king max tames the beasts and eventually returns home to find his supper waiting for him this iconic book explores themes of imagination adventure and the complex emotions of childhood all captured through sendaks whimsical illustrations and story
1,2,The Very Hungry Caterpillar,Eric Carle,1969,4.34,"The Very Hungry Caterpillar tells the story of a caterpillar who eats through a variety of foods before eventually becoming a butterfly. Eric Carle’s use of colorful collage illustrations and rhythmic text has made this book a beloved classic for young readers. The simple, engaging story introduces children to days of the week, counting, and the concept of metamorphosis. It’s a staple in early childhood education.",the very hungry caterpillar tells the story of a caterpillar who eats through a variety of foods before eventually becoming a butterfly eric carles use of colorful collage illustrations and rhythmic text has made this book a beloved classic for young readers the simple engaging story introduces children to days of the week counting and the concept of metamorphosis its a staple in early childhood education

In [53]:
phrase = df.Description_clean.iloc[0]
phrase

'where the wild things are follows max a young boy who after being sent to his room for misbehaving imagines sailing to an island filled with wild creatures as their king max tames the beasts and eventually returns home to find his supper waiting for him this iconic book explores themes of imagination adventure and the complex emotions of childhood all captured through sendaks whimsical illustrations and story'

In [65]:
doc1 = nlp(phrase)
doc1

where the wild things are follows max a young boy who after being sent to his room for misbehaving imagines sailing to an island filled with wild creatures as their king max tames the beasts and eventually returns home to find his supper waiting for him this iconic book explores themes of imagination adventure and the complex emotions of childhood all captured through sendaks whimsical illustrations and story

In [66]:
# lammetize, and filter out stop words
norm = [token.lemma_ for token in doc1 if not token.is_stop]
" ".join(norm)

'wild thing follow max young boy send room misbehave imago sail island fill wild creature king max tame beast eventually return home find supper wait iconic book explore theme imagination adventure complex emotion childhood capture sendak whimsical illustration story'

In [67]:
#part of speech tagging, and filter out stop words
norm1 =[token.text for token in doc1 if token.pos_ in ['NOUN', 'VERB', 'ADJ']]
" ".join(norm1)

'wild things follows young boy sent room misbehaving imagines sailing island filled wild creatures king tames beasts returns find supper waiting iconic book explores themes imagination adventure complex emotions childhood captured sendaks whimsical illustrations story'

## NLP Pipeline

In [81]:
# funtion to clean the description column of the dataframe
def lower_replace_special_char(series):
    # Convert to lowercase    
    output = series.str.lower()
    # Replace square brackets with empty string and remove special characters
    output = output.str.replace(r'\[.*?\]', '', regex=True)
    output = output.str.replace(r'[^\w\s]', '', regex=True)
    # Replace non-breaking spaces with regular spaces
    output = output.str.replace(r'\xa0', ' ', regex=True)
    return output

def lemma_token_stopword(text):
    doc = nlp(text)
    output = [token.lemma_ for token in doc if not token.is_stop]
    output = " ".join(output)
    return output

def filter_pos(text, pos_tags=['NOUN', 'VERB', 'ADJ']):
    doc = nlp(text)
    output =[token.text for token in doc if token.pos_ in pos_tags]
    output = " ".join(output)
    return output

#pipeline or abstract function to clean the description column of the dataframe
def nlp_pipeline(series):
    output = lower_replace_special_char(series)
    output = output.apply(lemma_token_stopword)
    output = output.apply(filter_pos, pos_tags=['NOUN', 'VERB', 'ADJ'])
    return output

In [82]:
df.Description_clean

0                            wild thing follow max young boy send room misbehave fill wild creature beast return home find supper wait iconic book explore theme imagination adventure complex emotion childhood capture whimsical illustration story
1                  hungry eat variety food butterfly use colorful collage illustration rhythmic text book beloved classic young reader simple engaging story introduce child day week counting concept metamorphosis staple early childhood education
2     give tree touching bittersweet story tree give boy course life boy grow take tree tree continue little left minimalist text illustration convey deep theme unconditional love selflessness passage time spark discussion relationship sacrifice
3                                             try convince reluctant character try dish green egg ham resistance classic story open new experience encourage child try thing playful illustration humorous dialogue fun educational read young reader
4                      moon gentle rhythmic bedtime story bunny say goodnight room moon quiet old lady whispering hush repetitive structure comfort ideal young child simple illustration clement nature story make beloved classic sleeptime reading
                                                                                                                           ...
95                               stone soup classic arrive village claim soup stone villager hesitant contribute ingredient pot create delicious meal story heartwarming lesson share community cooperation enhance beautiful watercolor illustration
96             light attic collection quirky explore wide range topic wit humor imagination funny thoughtful absurd carry sense wonder creativity silverstein distinctive voice whimsical illustration book timeless collection entertain child adult
97                                                                book year uncover secret past arrival mysterious sirius black dark truth face fear thrilling installment explore theme loyalty friendship identity mark turning point magical world
98                                                                       secret second book second year uncover chamber school mysterious event unfold uncover dark secret school theme courage friendship stand right explore grip magical adventure
99                      retelling classic norwegian greedy reach green come clever strategy trick troll teach child lesson teamwork bravery cleverness galdone illustration simple rhythmic text bring tale life accessible entertaining young reader
Name: Description_clean, Length: 100, dtype: str

In [83]:
df['Description_clean'] = nlp_pipeline(df.Description_clean)

In [84]:
df.head(2)

,Ranking,Title,Author,Year,Rating,Description,Description_clean
0,1,Where the Wild Things Are,Maurice Sendak,1963,4.25,"Where the Wild Things Are follows Max, a young boy who, after being sent to his room for misbehaving, imagines sailing to an island filled with wild creatures. As their king, Max tames the beasts and eventually returns home to find his supper waiting for him. This iconic book explores themes of imagination, adventure, and the complex emotions of childhood, all captured through Sendak's whimsical illustrations and story.",wild thing follow max young boy send room misbehave fill wild creature beast return home find supper wait iconic book explore theme imagination adventure complex emotion childhood capture whimsical illustration story
1,2,The Very Hungry Caterpillar,Eric Carle,1969,4.34,"The Very Hungry Caterpillar tells the story of a caterpillar who eats through a variety of foods before eventually becoming a butterfly. Eric Carle’s use of colorful collage illustrations and rhythmic text has made this book a beloved classic for young readers. The simple, engaging story introduces children to days of the week, counting, and the concept of metamorphosis. It’s a staple in early childhood education.",hungry eat variety food butterfly use colorful collage illustration rhythmic text book beloved classic young reader simple engaging story introduce child day week count concept metamorphosis staple early childhood education